# Generated by Django 4.2.25 on 2025-10-21 19:25

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresource',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or requirements'),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='campaign_slogan',
            field=models.TextField(help_text='Enter campaign slogan'),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='candidate_photo',
            field=models.ImageField(help_text='Upload candidate photo (max 5MB, formats: jpg, jpeg, png, gif)', upload_to='resources/photos/', validators=[orders.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='party_logo',
            field=models.ImageField(help_text='Upload party logo (max 5MB, formats: jpg, jpeg, png, gif)', upload_to='resources/logos/', validators=[orders.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='preferred_date',
            field=models.DateField(help_text='Preferred date for campaign'),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='whatsapp_number',
            field=models.CharField(help_text='WhatsApp contact number', max_length=15),
        ),
    ]
