# Generated by Django 4.2.25 on 2025-10-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_resourcefielddefinition'),
        ('orders', '0002_alter_orderresource_additional_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicResourceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.IntegerField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='dynamic_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.resourcefielddefinition')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_resources', to='orders.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['order_item'], name='orders_dyna_order_i_00099a_idx')],
                'unique_together': {('order_item', 'field_definition')},
            },
        ),
    ]
