# Generated by Django 4.2.25 on 2025-10-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_checklisttemplateitem'),
        ('orders', '0003_dynamicresourcesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template_item',
            field=models.ForeignKey(blank=True, help_text='Reference to the template item this was created from', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.checklisttemplateitem'),
        ),
    ]
