# Generated by Django 4.2.25 on 2025-10-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_checklistitem_is_optional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='Razorpay', max_length=50)),
                ('transaction_id', models.CharField(help_text='Razorpay payment ID or other transaction ID', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('invoice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('metadata', models.JSONField(default=dict, help_text='Store additional payment details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Payment histories',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['invoice_number'], name='orders_paym_invoice_1b670e_idx'), models.Index(fields=['payment_date'], name='orders_paym_payment_c9e1a7_idx'), models.Index(fields=['status'], name='orders_paym_status_477de0_idx')],
            },
        ),
    ]
