# Generated by Django 4.2.25 on 2025-11-02 21:29

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicresourcesubmission',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='user_resources/dynamic/'),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='candidate_photo',
            field=models.ImageField(help_text='Upload candidate photo (max 5MB, formats: jpg, jpeg, png, gif)', upload_to='user_resources/photos/', validators=[orders.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='party_logo',
            field=models.ImageField(help_text='Upload party logo (max 5MB, formats: jpg, jpeg, png, gif)', upload_to='user_resources/logos/', validators=[orders.models.validate_image_file]),
        ),
    ]
