# Generated by Django 4.2.25 on 2025-11-04 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_alter_dynamicresourcesubmission_file_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('is_manual_change', models.BooleanField(default=False, help_text='True if admin manually changed status')),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('razorpay', 'Razorpay'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID, cheque number, etc.', max_length=100)),
                ('payment_proof', models.FileField(blank=True, help_text='Upload payment receipt or proof', null=True, upload_to='payment_proofs/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin/staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin or staff who created this manual order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_manual_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('website', 'Website'), ('phone_call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('walk_in', 'Walk-in'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference number for manual payments', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_resources', 'Pending Resources'), ('ready_for_processing', 'Ready for Processing'), ('assigned', 'Assigned to Staff'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending_payment', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_manual_order'], name='orders_orde_is_manu_8755d7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_source'], name='orders_orde_order_s_6943b7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='orders_orde_created_780f95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='orders_orde_priorit_b622f0_idx'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
    ]
