# Generated by Django 4.2.25 on 2025-10-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0002_alter_campaign_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('number', 'Number'), ('document', 'Document')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('max_file_size_mb', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='products_re_content_bea432_idx'), models.Index(fields=['order'], name='products_re_order_1ee488_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name')},
            },
        ),
    ]
