# Generated by Django 4.2.25 on 2025-10-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0004_checklisttemplateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='products_pr_content_19215a_idx'), models.Index(fields=['order'], name='products_pr_order_2597cf_idx'), models.Index(fields=['is_primary'], name='products_pr_is_prim_b891de_idx')],
            },
        ),
    ]
