# Generated by Django 4.2.25 on 2025-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deliverables',
            field=models.JSONField(default=list, help_text='List of campaign deliverables'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='features',
            field=models.JSONField(default=list, help_text='List of campaign features'),
        ),
        migrations.AddField(
            model_name='package',
            name='deliverables',
            field=models.JSONField(default=list, help_text='List of package deliverables'),
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.JSONField(default=list, help_text='List of package features'),
        ),
    ]
