# Generated by Django 4.2.25 on 2025-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_campaign_deliverables_campaign_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefielddefinition',
            name='field_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('number', 'Number'), ('document', 'Document'), ('phone', 'Phone Number'), ('date', 'Date')], max_length=20),
        ),
    ]
