# Generated by Django 4.2.25 on 2025-11-02 19:46

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_resourcefielddefinition_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['popular_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['popular_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular to feature on homepage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='popular_order',
            field=models.IntegerField(default=0, help_text='Order in popular section (1-3)'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular to feature on homepage'),
        ),
        migrations.AddField(
            model_name='package',
            name='popular_order',
            field=models.IntegerField(default=0, help_text='Order in popular section (1-3)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', validators=[products.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_popular', 'popular_order'], name='products_ca_is_popu_485618_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='products_ca_created_2ec1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_popular', 'popular_order'], name='products_pa_is_popu_9d7be9_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['-created_at'], name='products_pa_created_ee8cf5_idx'),
        ),
    ]
